name: firebase_dart_flutter
description: A port of the Firebase database, auth and storage client to pure Dart code for use on flutter
version: 1.1.12
homepage: https://github.com/appsup-dart/firebase_dart

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_dart: ^1.3.0
  platform_info: ^5.0.0
  path_provider: ^2.0.0
  hive: ^2.0.0
  package_info: ^2.0.0
  google_sign_in: ^6.0.0
  sign_in_with_apple: ^6.0.0
  url_launcher: ^6.0.0
  logging: ^1.0.2
  flutter_apns_only: ^1.0.0
  crypto: ^3.0.3
  app_links: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: be.appsup.firebase_dart_flutter
        pluginClass: FirebaseDartFlutterPlugin
